Numpy
  NumPy (Numerical Python) is a powerful Python library

*  Working with large numerical arrays and matrices
*   Enabling vectorized computations


Arrays:

In [ ]:
import numpy as np
import sys

In [ ]:
my_list = [1,2,3,4,5,6,7]
my_list

[1, 2, 3, 4, 5, 6, 7]

In [ ]:
arr = np.array(my_list)   #1D array
print(arr)

[1 2 3 4 5 6 7]


2-D array

In [ ]:
b = np.array([[1,2],[3,4] ])
print(b)

[[1 2]
 [3 4]]


In [ ]:
import numpy as np
import sys

my_list = [1, 2, 3, 4]
arr = np.array(my_list, dtype=np.int8)

print(f"arr: {arr}")
print(f"sys.getsizeof: {sys.getsizeof(arr)} bytes")  # Metadata + pointer
print(f"arr.nbytes: {arr.nbytes} bytes")             # Actual data size


arr: [1 2 3 4]
sys.getsizeof: 116 bytes
arr.nbytes: 4 bytes


In [ ]:
zeroes = np.zeros((2,3))         #All zeroes
print(zeroes)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ones = np.ones((2,3))           #All ones
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
full_arr = np.full((2, 2), 7)          #fill with custom values
print("Full:\n", full_arr)


Full:
 [[7 7]
 [7 7]]


In [ ]:
eye_arr = np.eye(3)                                     #identity array
print("Identity Matrix:\n", eye_arr)


Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
linspace_arr = np.linspace(0, 1, 5)                     # Evenly spaced
print("Linspace:", linspace_arr)


Linspace: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
np.random.rand(5)                      #Random Floats

array([0.73172623, 0.91567754, 0.55768633, 0.62260482, 0.85177848])

In [ ]:
randint_arr = np.random.randint(1, 100, size=(2, 3))                      # Random Integers
print("Random Integers:\n", randint_arr)

Random Integers:
 [[19 39 86]
 [48 21 94]]


In [ ]:
func_arr = np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)        # Generate from some function
print("From Function:\n", func_arr)

From Function:
 [[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
a = np.arange(6)                                # Reshape an array
reshaped = a.reshape((2, 3))
print("Original:", a)
print("Reshaped:\n", reshaped)

Original: [0 1 2 3 4 5]
Reshaped:
 [[0 1 2]
 [3 4 5]]


In [ ]:
arr = np.arange(24)           # Creates array from 0 to 23 (24 elements)
arr3d = arr.reshape((2, 3, 4)) # Reshape to 3D: 2 matrices of 3 rows × 4 columns

print("3D Array shape:", arr3d.shape)
print("3D Array:\n", arr3d)

3D Array shape: (2, 3, 4)
3D Array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


np.ravel() returns a flattened 1D view (or copy) of a NumPy array, regardless of how many dimensions it originally had.

In [ ]:

arr = np.array([[1, 2, 3], [4, 5, 6]])                   #
flat = np.ravel(arr)

print("Original:\n", arr)
print("Flattened with ravel():", flat)

Original:
 [[1 2 3]
 [4 5 6]]
Flattened with ravel(): [1 2 3 4 5 6]


np.sort() returns a new sorted array (original stays unchanged).



In [ ]:
arr = np.array([5, 1, 4, 2])
sorted_arr = np.sort(arr)

print("Original:", arr)
print("Sorted:", sorted_arr)

Original: [5 1 4 2]
Sorted: [1 2 4 5]


In-Place Sorting with .sort()

In [ ]:
arr.sort()
print("In-place sorted:", arr)

In-place sorted: [1 2 4 5]


In [ ]:
arr2d = np.array([[3, 1, 2], [6, 5, 4]])                     # 2D array

print("Sort rows (axis=1):\n", np.sort(arr2d, axis=1))
print("Sort columns (axis=0):\n", np.sort(arr2d, axis=0))

Sort rows (axis=1):
 [[1 2 3]
 [4 5 6]]
Sort columns (axis=0):
 [[3 1 2]
 [6 5 4]]


np.argsort() — Sorting Indices



In [ ]:
arr = np.array([40, 10, 30, 20])
indices = np.argsort(arr)

print("Indices that would sort:", indices)
print("Sorted using indices:", arr[indices])

Indices that would sort: [1 3 2 0]
Sorted using indices: [10 20 30 40]


Finding shape of array

In [ ]:
arr.shape


(4,)

Indexing and Selection:





Indexing for 2D array

In [ ]:
b = np.array([[1, 2, 3],
              [4, 5, 6]])

print(b[0, 1])   # 2 (row 0, col 1)
print(b[1][2])   # 6 (same as b[1, 2])


2
6


Slicing 2D Arrays

In [ ]:
print(b[0, :])   # [1 2 3] → entire first row
print(b[:, 1])   # [2 5]   → second column
print(b[0:2, 1:3])  # [[2 3], [5 6]] → submatrix

[1 2 3]
[2 5]
[[2 3]
 [5 6]]


Conditional Selection:
  a powerful feature that allows you to filter and manipulate arrays based on

*    a powerful feature that allows you to filter and manipulate arrays based on conditions





In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[arr > 25])        # [30 40 50]

[30 40 50]


Finding Elements:

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
found = arr[arr == 30]

print("Found:", found)   # [30]

Found: [30]


Operations:

In [30]:
#Arithmetic Operations
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a + b)    # [11 22 33]
print(a * b)    # [10 40 90]
print(b - a)    # [9 18 27]
print(b / a)    # [10. 10. 10.]
print(a ** 2)   # [1 4 9]

[11 22 33]
[10 40 90]
[ 9 18 27]
[10. 10. 10.]
[1 4 9]


In [31]:
# Finding the logs of every element:

np.log(arr)


array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301])

In [32]:
# Square root:

np.sqrt(arr)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [33]:
# Exponential:

np.exp(arr)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21])

In [34]:
# Finding Sum:

np.sum(arr)

np.int64(150)

In [35]:
np.sum(arr2d, axis=0)

array([9, 6, 6])